import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import { useCart } from '../context/CartContext'
import { useEffect, useState } from 'react'
import axios from 'axios'
import CartItem from '../components/CartItem'
import Link from 'next/link'
import { useAuth } from '../context/AuthContext'

export default function Cart() {
  const { cart, removeFromCart } = useCart()
  const { authUser } = useAuth()
  const [products, setProducts] = useState<any[]>([])

  useEffect(() => {
    if (!cart) return
    ;(async () => {
      axios
        .get(process.env.NEXT_PUBLIC_API_URL + '/products')
        .then((res) => {
          setProducts(
            res.data.data.filter((item: any) => cart.map((c: any) => c.id).includes(item.id)),
          )
        })
        .catch((e) => console.error(e))
    })()
  }, [cart])

  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container">
        {products.map(
          (product) =>
            cart.find((c: any) => c.id === product.id) && (
              <CartItem
                product={product}
                key={product.id}
                qty={cart.find((c: any) => c.id === product.id).qty}
              />
            ),
        )}
        <div
          style={{
            background: '#141E26',
            textAlign: 'center',
            marginTop: -20,
            paddingTop: 25,
            paddingBottom: 25,
          }}
        >
          Total: <b>{cart.reduce((prev: any, curr: any) => prev + curr.price, 0)}$</b>
        </div>
        {authUser ? (
          <button onClick={() => console.log('ok')}>Proceed order</button>
        ) : (
          <p>
            Please <Link href={'/login'}>login</Link> to proceed order
          </p>
        )}
      </main>
    </>
  )
}
