import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import ArticleCard from '../components/Navbar/ArticleCard'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  const [products, setProducts] = useState<any[]>([])

  useEffect(() => {
    axios
      .get(process.env.NEXT_PUBLIC_API_URL + '/products')
      .then((res) => setProducts(res.data.data))
      .catch((e) => console.error(e))
  }, [])

  return (
    <>
      <Head>
        <title>Livecampus FrameworkJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container">
        <h1>Some of our articles</h1>
        <Link href="/products">Want more ? Visit our products page !</Link>
        <div className="grid">
          {products.map((product) => (
            <ArticleCard product={product} key={product.id} />
          ))}
        </div>
      </main>
    </>
  )
}
